swagger: '2.0'
info:
  description: 'A sample object containing standard properties'
  title: 'Sample: flat object'

definitions:

  FlatObject:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        description: Some ID
        example: 'xyz'
      name:
        type: string
        description: 'Some name'
        example: 'Prawn'

