swagger: '2.0'
info:
  description: >-
    Test Swagger yaml
  version: ${api-version}
  title: Example API - Flat
  contact:
    email: example@text.com
host: test.sample.com
basePath: /v1/sample
schemes:
  - https
paths:
  /sample:
    post:
      tags:
        - sample
        - test
      summary: Sample endpoint
      description: Sample endpoint.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: request body
          required: true
          schema:
            $ref: '#/definitions/SampleRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/SampleResponse'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

definitions:

  FlatRequest:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: string
        description: Some ID
        example: "3"
      name:
        type: string
        description: Some name
        example: 'Prawn'

  FlatResponse:
    type: object
    required:
      - code
    properties:
      code:
        type: string
        description: Response code
        example: '123'
      message:
        type: string
        description: A verbose message
