swagger: '2.0'
info:
  description: >-
    Test Swagger yaml
  version: ${api-version}
  title: Example API - Nested
  contact:
    email: example@text.com
host: test.sample.com
basePath: /v1/sample
schemes:
  - https
paths:
  /sample:
    post:
      tags:
        - sample
        - test
      summary: Sample endpoint
      description: Sample endpoint.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: request body
          required: true
          schema:
            $ref: '#/definitions/NestedRequest'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/NestedResponse'
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error

definitions:

  ArrayOfUsers:
    type: object
    required:
      - group_id
      - group_name
      - contacts
    properties:
      group_id:
        type: integer
        description: Some ID
        example: 3
      group_name:
        type: string
        description: Some name
        example: 'Prawns'
      contacts_schema:
        type: array
        items:
          $ref: '#/definitions/ContactDetails'

  ContactDetails:
    type: object
    required:
      - email_address
    properties:
      first_name:
        type: string
      last_name:
        type: string
      email_address:
        type: string
      phone_number:
        type: string
      spam:
        type: boolean
        description: Send this person spam?
